server:
  port: 5000
spring:
  application:
    name: config-server
  cloud:
#    stream:
#      kafka:
#        binder:
#          #Kafka的服务端列表
#          brokers: sanleny70.com:9092,sanleny71.com:9092,sanleny72.com:9092
    config:
      server:
        git:
          ##定义去拉取配置的地址
#          uri: F:\Project\configs
          uri: https://github.com/SanLeny/sanleny-springcloud-config.git
#          uri: http://gitlab.sanleny.com/web/sanleny-springcloud-config.git
#          username: 308644773
#          password: a123!@#A
          #定义为强制向git去拉取配置
          force-pull: true
        ##启用加密算法
#        encrypt:
#          enabled: true
#  #引入账号密码机制
#  security:
#    user:
#      name: sanleny
#      password: 123456
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
##开启端口
management:
  endpoints:
    web:
      exposure:
        include: "*"

##配置中心和注册中心结合使用 把自己当成客户端注册到注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
    enabled: true

#spring:
#  application:
#    name: app-provider-config
#  cloud:
#    config:
#      enabled: true
#      server:
#        svn:
#          uri: http://ip:port/svn/mogo/Coding/app-hotpoint-parent/app-global-config
#          username: username
#          password: password
#          default-label: config-repo