server:
  port: 5000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          ##定义去拉取配置的地址
#          uri: F:\Project\configs
          uri: https://github.com/SanLeny/sanleny-pringcloud-config.git
          #定义为强制向git去拉取配置
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
