spring:
  application:
    name: user-sample
  redis:
    host: 10.114.130.216
    port: 6379
    database: 0
server:
  port: 9003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
token:
  jwt:
    key: nick123
    iss: 11
    expm: 10
management:
  endpoints:
    web:
      exposure:
        include: "*"