spring:
#  zipkin:
#    base-url: http://localhost:9411
  application:
    name: feign-sample
server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread :
            timeoutInMilliseconds: 1000
management:
  endpoints:
    web:
      exposure:
        include: "*"