server:
  port: 7004
spring:
  application:
    name: zipkin-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:logback-spring.xml
#zipkin:
#  collector:
#    sample-rate: 1.0
#    http:
#      enabled: false
#    rabbitmq:
#      addresses: localhost:5672
#      password: guest
#      username: guest
#      queue: zipkin
#      virtual-host: /
#    kafka:
#      # Kafka bootstrap broker list, comma-separated host:port values. Setting this activates the
#      bootstrap-servers: sanleny70.com:9092,sanleny71.com:9092,sanleny72.com:9092
#      # Name of topic to poll for spans
#      topic: zipkin
#      # Consumer group this process is consuming on behalf of.
#      group-id: zipkin
#      # Count of consumer threads consuming the topic
#      streams: 1
#  storage:
#    type: mysql
#    mysql:
#      host: localhost
#      port: 3306
#      username: root
#      password: Sin1/2=30
#      db: zipkin
#  storage:
#    type: elasticsearch
#    StorageComponent: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch
#      max-requests: 30
#      index: zipkin
#      index-shards: 3
#      index-replicas: 1
#      hosts: localhost:9200