spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
sanleny:
  ignore:
    urls:
      - /actuator/**
      - /auth/**