server:
  port: 8002
spring:
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
#定义开启端口
management:
  endpoints:
    web:
      exposure:
        #让客户端支持env和refresh方式
        include: env,refresh
