server:
  port: 8002
spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          #Kafka的服务端列表
#          brokers: sanleny70.com:9092,sanleny71.com:9092,sanleny72.com:9092
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
#定义开启端口
management:
  endpoints:
    web:
      exposure:
        #让客户端支持env和refresh方式
        include: env,refresh
