server:
  port: 8002
spring:
#  kafka:
#    #Kafka的服务端代理列表
#    bootstrap-servers: sanleny70.com:9092,sanleny71.com:9092,sanleny72.com:9092
  application:
    name: config-client
#定义开启端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
